spring:
  profiles:
    active: native
  security:
    user:
      name: root
      password: changeme
server:
  port: 8001
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8010/eureka/